### ISSUE TITLE
GIFs not showing

### ISSUE THREAD

**Issue by ghost** [SamR1/python-twittfeed#32]
This post got boosted.
https://mstdn.social/@stux/108778453880693206
But the RSS feed entry shows just a title and some post text , no .gif file or any indication of attachment.

**Comment by ghost** [comment]
Same with MP4 attachment posts.
https://bitcoinhackers.org/@farooq/108778808620485314

**Comment by SamR1** [comment]
Hi!

it's fixed in [v0.7.2](https://github.com/SamR1/python-twootfeed/releases/tag/v0.7.2), sorry for the delay.

**Comment by ghost** [comment]
Thanks Sam!
